name: flutter_rounded_date_picker
description: The Flutter plugin that help you can choose dates and years with rounded calendars and customizable themes.
version: 2.0.0
author: benznest <benz7nbet@gmail.com>
homepage: https://github.com/benznest/flutter_rounded_date_picker

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
